/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import '@ionic/core';
import 'ionicons';
import {
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppHome {
    'history': RouterHistory;
  }
  interface AppHomeAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface AppProfile {
    'name': string;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppRoot {
    'history': RouterHistory;
  }
  interface AppRootAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface ChatRoom {
    'history': RouterHistory;
  }
  interface ChatRoomAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
  }

  interface SignIn {}
  interface SignInAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'ChatRoom': Components.ChatRoom;
    'SignIn': Components.SignIn;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'chat-room': Components.ChatRoomAttributes;
    'sign-in': Components.SignInAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLChatRoomElement extends Components.ChatRoom, HTMLStencilElement {}
  var HTMLChatRoomElement: {
    prototype: HTMLChatRoomElement;
    new (): HTMLChatRoomElement;
  };

  interface HTMLSignInElement extends Components.SignIn, HTMLStencilElement {}
  var HTMLSignInElement: {
    prototype: HTMLSignInElement;
    new (): HTMLSignInElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'chat-room': HTMLChatRoomElement
    'sign-in': HTMLSignInElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'chat-room': HTMLChatRoomElement;
    'sign-in': HTMLSignInElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
